#!/bin/sh

### BEGIN INIT INFO
# Provides:          clamsmtp
# Required-Start:    $local_fs $network $remote_fs clamav-clamd
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the clamsmtp
# Description:       starts clamsmtp using start-stop-daemon
### END INIT INFO

prefix=@@PREFIX@@
DAEMON=${prefix}/sbin/clamsmtpd
NAME=clamsmtp
DESC=clamsmtp
USER=clamav
PIDFILE=/appls/clamsmtp/run/$NAME.pid
DAEMON_OPTS="-p ${PIDFILE}"

PATH=${prefix}/sbin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
test -x $DAEMON || exit 0
set -e

. /lib/lsb/init-functions

start_clamsmtp()
{
 log_daemon_msg "Starting ClamSMTP" "$DESC"
 if start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
                --exec $DAEMON -- $DAEMON_OPTS >/dev/null 2>&1; then
   log_end_msg 0
 else
   log_end_msg 1
fi
}

stop_clamsmtp()
{
 log_daemon_msg "Stopping ClamSMTP" "$DESC"
 if start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
                --exec $DAEMON >/dev/null 2>&1; then
   log_end_msg 0
 else
   log_end_msg 1
 fi
}

reload_clamsmtp()
{
 log_daemon_msg "Reloading ClamSMTP configuration" "$DESC"
 if start-stop-daemon --stop --signal HUP --quiet --pidfile ${PIDFILE} \
                --exec $DAEMON >/dev/null 2>&1; then
   log_end_msg 0
 else
   log_end_msg 1
 fi
}

case "$1" in
  start)
    start_clamsmtp
  ;;
  stop)
    stop_clamsmtp
  ;;
  restart|force-reload)
    stop_clamsmtp
    sleep 3
    start_clamsmtp
  ;;
  reload)
    reload_clamsmtp
  ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
    exit 1
  ;;
esac

exit 0
