#!/bin/sh

### BEGIN INIT INFO
# Provides:          clamav-clamd
# Required-Start:    $local_fs $network $remote_fs rsyslog
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the clamav-clamd
# Description:       starts clamav-clamd using start-stop-daemon
### END INIT INFO

prefix=@@PREFIX@@
DAEMON=${prefix}/sbin/clamd
USER=clamav
NAME=clamav-clamd
DESC=clamav-clamd
PIDFILE=${prefix}/run/$NAME.pid

PATH=${prefix}/sbin:/sbin:/bin:/usr/sbin:/usr/bin
test -x $DAEMON || exit 1
set -e

. /lib/lsb/init-functions

start_clamav()
{
	log_daemon_msg "Starting ClamAV" "$DESC"
	if start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
			--exec $DAEMON -- $DAEMON_OPTS >/dev/null 2>&1; then
		log_end_msg 0
	else
		log_end_msg 1
	i
}

stop_clamav()
{
	log_daemon_msg "Stopping ClamAV" "$DESC"
	if start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
			--exec $DAEMON >/dev/null 2>&1; then
		log_end_msg 0
	else
		log_end_msg 1
	fi
}

reload_clamav()
{
	log_daemon_msg "Reloading ClamAV configuration" "$DESC"
	if start-stop-daemon --stop --signal HUP --quiet --pidfile ${PIDFILE} \
			--exec $DAEMON >/dev/null 2>&1; then
		log_end_msg 0
	else
		log_end_msg 1
	fi
}

case "$1" in
	start)
		start_clamav
	;;

	stop)
		stop_clamav
	;;

	restart|force-reload)
		stop_clamav
		sleep 2
		start_clamav
	;;

	reload)
		reload_clamav
	;;

	*)
		N=/etc/init.d/$NAME
		echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
		exit 1
	;;
esac

exit 0
