#!/bin/sh

### BEGIN INIT INFO
# Provides:          clamav-freshclam
# Required-Start:    $local_fs $network $remote_fs clamav-clamd
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the clamav-freshclam
# Description:       starts clamav-freshclam using start-stop-daemon
### END INIT INFO

prefix=@@PREFIX@@
DAEMON=${prefix}/bin/freshclam
DAEMON_OPTS="-d"
USER=clamav
NAME=clamav-freshclam
DESC=clamav-freshclam
PIDFILE=${prefix}/run/$NAME.pid

PATH=${prefix}/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
test -x $DAEMON || exit 0
set -e

. /lib/lsb/init-functions

start_freshclam()
{
 log_daemon_msg "Starting Freshclam" "$DESC"
 if start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
                --exec $DAEMON -- $DAEMON_OPTS >/dev/null 2>&1; then
   log_end_msg 0
 else
   log_end_msg 1
fi
}

stop_freshclam()
{
 log_daemon_msg "Stopping Freshclam" "$DESC"
 if start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
                --exec $DAEMON >/dev/null 2>&1; then
   log_end_msg 0
 else
   log_end_msg 1
 fi
}

reload_freshclam()
{
 log_daemon_msg "Reloading Freshclam configuration" "$DESC"
 if start-stop-daemon --stop --signal HUP --quiet --pidfile ${PIDFILE} \
                --exec $DAEMON >/dev/null 2>&1; then
   log_end_msg 0
 else
   log_end_msg 1
 fi
}

case "$1" in
  start)
    start_freshclam
  ;;
  stop)
    stop_freshclam
  ;;
  restart|force-reload)
    stop_freshclam
    sleep 3
    start_freshclam
  ;;
  reload)
    reload_freshclam
  ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
    exit 1
  ;;
esac

exit 0
