#!/bin/sh

### BEGIN INIT INFO
# Provides:          dovecot
# Required-Start:    $local_fs $remote_fs $network $syslog mysql
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Dovecot init script
# Description:       Init script for dovecot services
### END INIT INFO

prefix=@@PREFIX@@
DAEMON=${prefix}/sbin/dovecot
NAME=dovecot

PATH=${prefix}/sbin:/sbin:/bin:/usr/sbin:/usr/bin
test -x $DAEMON || exit 1
set -e

. /lib/lsb/init-functions

base_dir="$(${DAEMON} config -h base_dir 2>/dev/null)"
pidfile="${base_dir}/master.pid"

start_dovecot() {
	log_daemon_msg "Starting Dovecot IMAP/POP3 server" "$NAME"
	if $($DAEMON >/dev/null 2>&1) ; then
		log_end_msg 0
	else
		log_end_msg 1
	fi
}

stop_dovecot() {
	log_daemon_msg "Stopping Dovecot IMAP/POP3 server" "$NAME"
	if [ "x$running" == "xyes" ]; then
		/bin/kill $(cat $pidfile) >/dev/null 2>&1
		if [ $? -eq 0 ]; then
			log_end_msg 0
		else
			log_end_msg 1
		fi
	else
		log_failure_msg "Dovecot server process is not running!"
	fi
}

reload_dovecot() {
	log_daemon_msg "Reloading Dovecot IMAP/POP3 server configuration" "$NAME"
	if [ "x$running" == "xyes" ]; then
		/bin/kill -HUP $(cat $pidfile) >/dev/null 2>&1
		if [ $? -eq 0 ]; then
			log_end_msg 0
		else
			log_end_msg 1
		fi
	else
		log_failure_msg "Dovecot server process is not running!"
	fi
}

if [ -r $pidfile ]; then
	running=yes
else
	running=no
fi

case "$1" in
	start)
		start_dovecot
	;;

	stop)
		stop_dovecot
	;;

	reload)
		reload_dovecot

	;;

	restart|force-reload)
		stop_dovecot
		sleep 2
		start_dovecot
	;;

	*)
		N=/etc/init.d/$NAME
		echo "Usage: $N {start|stop|reload|restart|force-reload}" >&2
		exit 1
	;;
esac

exit 0
