#!/bin/sh

### BEGIN INIT INFO
# Provides:          dovecot
# Required-Start:    $local_fs $remote_fs $network $syslog mysql
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Dovecot init script
# Description:       Init script for dovecot services
### END INIT INFO

prefix=@@PREFIX@@
DAEMON=${prefix}/sbin/dovecot
NAME=dovecot

PATH=${prefix}/sbin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
test -x $DAEMON || exit 0
set -e

. /lib/lsb/init-functions

base_dir="$(${DAEMON} config -h base_dir 2>/dev/null)"
pidfile="${base_dir}/master.pid"

if test -f $pidfile; then
  running=yes
else
  running=no
fi

case "$1" in
  start)
    log_daemon_msg "Starting Dovecot IMAP/POP3 server" "$NAME"
    $DAEMON
    if [ $? -eq 0 ]; then
	log_end_msg 0
    else
	log_end_msg 1
    fi
    ;;
  stop)
    if test $running = yes; then
      log_daemon_msg "Stopping Dovecot IMAP/POP3 server" "$NAME"
      kill $(cat $pidfile)
      log_end_msg 0
    else
      log_failure_msg "Dovecot server process is not running!"
    fi
    ;;
  reload)
    if test $running = yes; then
      log_daemon_msg "Reloading Dovecot IMAP/POP3 server configuration" "$NAME"
      kill -HUP $(cat $pidfile)
      log_end_msg 0
    else
      log_failure_msg "Dovecot server process is not running!"
    fi
    ;;
  restart|force-reload)
    log_daemon_msg "Restarting Dovecot IMAP/POP3 server" "$NAME"
    if test $running = yes; then
      kill $(cat $pidfile)
      sleep 1
    fi
    $DAEMON
    if [ $? -eq 0 ]; then
        log_end_msg 0
    else
        log_end_msg 1
    fi
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|reload|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
