#! /bin/sh

### BEGIN INIT INFO
# Provides:          mongodb
# Required-Start:    $local_fs $network $remote_fs rsyslog
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the mongodb server
# Description:       starts mongodb using start-stop-daemon
### END INIT INFO

prefix=@@PREFIX@@
DAEMON="${prefix}/sbin/mongod"
CONFIGFILE="${prefix}/conf/mongod.conf"
DAEMON_USER=mongodb
DAEMON_OPTS="--config ${CONFIGFILE}"
NAME=mongodb
DESC=mongodb

PATH=${prefix}/sbin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
test -x $DAEMON || exit 0
set -e

. /lib/lsb/init-functions
ulimit -n 2048
pidfile="$(awk -F= '/^pidfilepath/ {print $2}' /appls/mongodb/conf/mongod.conf |tr -d ' ')"

start_mongodb()
{
 log_daemon_msg "Starting MongoDB server" "$DESC"
 if start-stop-daemon --start --quiet \
               --chuid ${DAEMON_USER} --exec ${DAEMON} -- ${DAEMON_OPTS} >/dev/null 2>&1; then
    log_end_msg 0
 else
    log_end_msg 1
 fi
}

stop_mongodb()
{
 log_daemon_msg "Stopping MongoDB server" "$DESC"
 if start-stop-daemon --stop --quiet --pidfile ${pidfile} \
               --user ${DAEMON_USER} --exec ${DAEMON} >/dev/null 2>&1; then
    log_end_msg 0
    rm -f ${pidfile} >/dev/null 2>&1
 else
    log_end_msg 1
 fi
}

case "$1" in
  start)
    start_mongodb
  ;;

  stop)
    stop_mongodb
  ;;

  restart|force-reload)
    stop_mongodb
    sleep 3
    start_mongodb
  ;;

  reload)
    log_daemon_msg "Reloading MongoDB server configurationi" "$DESC"
    if start-stop-daemon --stop --signal HUP --quiet --pidfile ${pidfile} \
                  --user ${DAEMON_USER} --exec ${DAEMON} >/dev/null 2>&1; then
       log_end_msg 0
    else
        log_end_msg 1
    fi
 ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
    exit 1
  ;;
esac

exit 0
