#! /bin/sh

### BEGIN INIT INFO
# Provides:          nginx
# Required-Start:    $local_fs $network $remote_fs rsyslog
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the nginx web server
# Description:       starts nginx using start-stop-daemon
### END INIT INFO

prefix=@@PREFIX@@
DAEMON=${prefix}/sbin/nginx
NAME=nginx
DESC=nginx

PATH=${prefix}/sbin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
test -x $DAEMON || exit 0
set -e

. /lib/lsb/init-functions
ulimit -n 2048

user=www
sanity()
{
 [ -d /var/log/nginx ] || mkdir -p /var/log/nginx
 chown ${user}.root -R /var/log/nginx
 chmod 0770 /var/log/nginx
 mkdir -p @@TMPSRV@@/nginx
 mkdir -p @@TMPSRV@@/nginx/fastcgi
 mkdir -p @@TMPSRV@@/nginx/client
 mkdir -p @@TMPSRV@@/nginx/proxy
 chown ${user}.root -R @@TMPSRV@@/nginx
 chmod 0770 @@TMPSRV@@/nginx
 chmod 0770 @@TMPSRV@@/nginx/fastcgi
 chmod 0770 @@TMPSRV@@/nginx/client
 chmod 0770 @@TMPSRV@@/nginx/proxy
}

start_nginx()
{
 log_daemon_msg "Starting nginx http/https server" "$DESC"
 if start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
           --exec $DAEMON -- $DAEMON_OPTS >/dev/null 2>&1; then
    log_end_msg 0
 else
    log_end_msg 1
 fi
}

stop_nginx()
{
 log_daemon_msg "Stopping nginx http/https server" "$DESC"
 if start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
               --exec $DAEMON >/dev/null 2>&1; then
    log_end_msg 0
 else
    log_end_msg 1
 fi
}

case "$1" in
  start)
    sanity
    start_nginx
  ;;

  stop)
    stop_nginx
  ;;

  restart|force-reload)
    stop_nginx
    sleep 3
    start_nginx
  ;;

  reload)
    echo -n "Reloading nginx http/https server configuration" "$DESC"
    if start-stop-daemon --stop --signal HUP --quiet --pidfile /var/run/$NAME.pid \
          --exec $DAEMON >/dev/null 2>&1; then
       log_end_msg 0
    else
        log_end_msg 1
    fi
 ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
    exit 1
  ;;
esac

exit 0
