#!/bin/sh

### BEGIN INIT INFO
# Provides:          php-fastcgi
# Required-Start:    $local_fs $network $remote_fs nginx
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts php-fastcgi server
# Description:       starts php-fastcgi using start-stop-daemon
### END INIT INFO

NAME=php-fastcgi
BIND=@@TMPSRV@@/php-fastcgi.socket
USER=www
PHP_FCGI_CHILDREN=5
PHP_FCGI_MAX_REQUESTS=512

PHP_CGI=@@DAEMON@@
PHP_CGI_NAME=$(basename $PHP_CGI)

PHP_CGI_ARGS="- USER=$USER PATH=/usr/local/bin:/usr/bin:/bin \
PHP_FCGI_CHILDREN=$PHP_FCGI_CHILDREN \
PHP_FCGI_MAX_REQUESTS=$PHP_FCGI_MAX_REQUESTS \
$PHP_CGI -q -b $BIND"

. /lib/lsb/init-functions
DISTRO=$(lsb_release -is 2>/dev/null || echo Debian)

TZ=
unset TZ
PIDFILE=/var/run/php-fastcgi.pid
set -e
ulimit -n 4096

sanity()
{
 mkdir -p @@TMPSRV@@/php/{log,sess,tmp,eaccelerator}
 chown ${USER}.${USER} -R @@TMPSRV@@/php
 chmod 0770 @@TMPSRV@@/php @@TMPSRV@@/php/{log,sess,tmp,eaccelerator}
}

running() {
 if [ -f ${PIDFILE} ]; then
   pid=$(sed 's/ //g' ${PIDFILE})
   exe=$(ls -l /proc/$pid/exe 2>/dev/null | sed 's/.* //;')
   if [ "$exe" = "$PHP_CGI" ]; then
      echo y
   fi
 fi
}

start() {
 local RUNNING=$(running)
 sanity
 if [ -n "$RUNNING" ]; then
   echo "$NAME already running"
   exit 1
 fi

 log_daemon_msg "Starting PHP Fastcgi Server" "$NAME"
 if start-stop-daemon --quiet --start --background --pidfile ${PIDFILE} \
          --make-pidfile --chuid $USER --exec /usr/bin/env -- $PHP_CGI_ARGS >/dev/null 2>&1; then
    log_end_msg 0
 else
    log_end_msg 1
 fi
}

stop() {
 local RUNNING=$(running)
 if [ -z "$RUNNING" ]; then
   echo "$NAME is already shutdown"
   exit 1
 fi

 log_daemon_msg "Stopping PHP Fastcgi Server" "$NAME"
 if start-stop-daemon --stop --pidfile ${PIDFILE} --signal 15 >/dev/null 2>&1; then
   rm -f ${PIDFILE}
   rm -f ${BIND}
   log_end_msg 0
 else
   log_end_msg 1
 fi
}

case "$1" in
    start)
      start
  ;;
    stop)
      stop
  ;;
    restart)
      stop
      sleep 3
      start
  ;;
    *)
      N=/etc/init.d/$NAME
      echo "Usage: $N {start|stop|restart}" >&2
      exit 1
  ;;
esac

exit 0
