#! /bin/sh

### BEGIN INIT INFO
# Provides:          postfix
# Required-Start:    $local_fs $remote_fs $network $syslog clamd mysql dovecot
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the postfix mail server
# Description:       starts postfix using start-stop-daemon
### END INIT INFO

prefix=@@PREFIX@@
DAEMON=${prefix}/sbin/postfix
pidfile=/var/spool/postfix/pid/master.pid
NAME=postfix

PATH=${prefix}/sbin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
test -x $DAEMON || exit 0
set -e

. /lib/lsb/init-functions

start_postfix()
{
 log_daemon_msg "Starting Postfix Mail Server" "$NAME"
 if start-stop-daemon --start --exec $DAEMON -- start >/dev/null 2>&1; then
    log_end_msg 0
 else
    log_end_msg 1
 fi
}

stop_postfix()
{
 log_daemon_msg "Stopping Postfix Mail Server" "$NAME"
 if ${DAEMON} stop >/dev/null 2>&1; then
    rm -f ${pidfile}
    log_end_msg 0
 else
    log_end_msg 1
 fi
}

case "$1" in
  start)
    start_postfix
  ;;

  stop)
    stop_postfix
  ;;

  restart|force-reload)
    stop_postfix
    sleep 2
    start_postfix
  ;;

  reload)
    echo -n "Reloading Postfix Mail Server configuration" "$NAME"
    if ${DAEMON} reload >/dev/null 2>&1; then
       log_end_msg 0
    else
       log_end_msg 1
    fi
 ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
    exit 1
  ;;
esac

exit 0
